### ISSUE TITLE
clicking on the Users Avatar on the profile page should allow the user to change said avatar

### ISSUE THREAD

**Issue by lappalal** [codeuniversity/code-intranet-issues#1]
<img width="1680" alt="screenshot 2017-10-10 11 31 29" src="https://user-images.githubusercontent.com/1348687/31379456-9873aa36-adae-11e7-8d61-8d983672c635.png">

Avatar placeholder on the top right. Clicking on it should open some sort of edit dialog.

**Comment by luhagel** [comment]
Fixed
