### ISSUE TITLE
Report an Issue button doesn't stick to bottom

### ISSUE THREAD

**Issue by slashmo** [codeuniversity/code-intranet-issues#11]
The "Report an issue" button on the page doesn't stick to the bottom if the user scrolls. Initially it's located at the bottom but after scrolling it just scrolls up with the rest of the content like you can see in the following screenshot:

<img width="841" alt="code-intranet-bug" src="https://user-images.githubusercontent.com/16192401/31490616-e5a67e0e-af44-11e7-9c2b-c1cb80e3450e.png">

**Comment by luhagel** [comment]
On it

**Comment by luhagel** [comment]
fixed
