### ISSUE TITLE
Visible scrollbars in chrome

### ISSUE THREAD

**Issue by ConstantinSchreiber** [codeuniversity/code-intranet-issues#12]
![2017-10-12_12-43-36](https://user-images.githubusercontent.com/15871093/31492548-cb03d8e2-af4b-11e7-9e45-d4f91bf49251.png)

Many scrollbars visible all over the place.

Tested on Win 10 + Chrome 61.0.3

**Comment by luhagel** [comment]
Currently looking for a workaround!

**Comment by luhagel** [comment]
Fixed, now they show when there is something to scroll 👍
