### ISSUE TITLE
Hyperlink stays colored after click

### ISSUE THREAD

**Issue by ConstantinSchreiber** [codeuniversity/code-intranet-issues#15]
![2017-10-12_18-57-39](https://user-images.githubusercontent.com/15871093/31508901-d2fa4d4a-af7f-11e7-8b02-7ab1306d9f22.png)

Not 100% sure if intended or Bug but hyperlinks to social networks stay colored after they are clicked.

**Comment by luhagel** [comment]
On in

**Comment by luhagel** [comment]
fixed with the next deployment
