### ISSUE TITLE
wiki content box is too small

### ISSUE THREAD

**Issue by pup** [codeuniversity/code-intranet-issues#16]
![image](https://user-images.githubusercontent.com/6078550/31518197-bcb13eda-af9e-11e7-95f5-e4893187f406.png)

pretty sure with this size, its not meant to be edited by humans

**Comment by pup** [comment]
and yeah i know it can be resized, it would just be nice to have it be larger by default

**Comment by luhagel** [comment]
no longer relevant; using confluence
