### ISSUE TITLE
Empty cell space in listing

### ISSUE THREAD

**Issue by freemanrepo** [codeuniversity/code-intranet-issues#24]
I tried to show it as much as I can.

![screen shot 2017-10-18 at 10 05 22 am](https://user-images.githubusercontent.com/1644696/31707326-43df7e8e-b3ec-11e7-9cf9-9b91e03fa040.png)

**Comment by luhagel** [comment]
Might need a few extra neon signs...
Looking into it!

**Comment by luhagel** [comment]
fixed with release-0.7.0
