### ISSUE TITLE
mouse should be a pointer on hovering the menu handle

### ISSUE THREAD

**Issue by lappalal** [codeuniversity/code-intranet-issues#3]
<img width="1680" alt="screenshot 2017-10-10 14 20 51" src="https://user-images.githubusercontent.com/1348687/31386217-4ef19a5e-adc6-11e7-9cb2-6a3b01ddd966.png">
<img width="123" alt="screenshot 2017-10-10 14 20 55" src="https://user-images.githubusercontent.com/1348687/31386218-4f0abe94-adc6-11e7-9dc3-8db038acaeab.png">

The handle should trigger the mouse to become a pointer on hover.

**Comment by luhagel** [comment]
fixed
