### ISSUE TITLE
Editing team members

### ISSUE THREAD

**Issue by AstiV** [codeuniversity/code-intranet-issues#32]
After applying for the project twice, team member can be accepted two times. Leads to the issue, that same team member is displayed two times in project view.
Nevertheless, although team member was accepted, they can neither see the project in their dashboard nor in their profile.

<img width="1280" alt="bildschirmfoto 2017-10-25 um 17 51 45" src="https://user-images.githubusercontent.com/15826773/32008979-031006cc-b9ae-11e7-937e-ab84a360e642.png">
<img width="870" alt="bildschirmfoto 2017-10-25 um 17 52 07" src="https://user-images.githubusercontent.com/15826773/32008981-032c174a-b9ae-11e7-90e2-3cdf3cd382bb.png">

**Comment by luhagel** [comment]
On it
