### ISSUE TITLE
Changing your profile photo is not possible

### ISSUE THREAD

**Issue by lappalal** [codeuniversity/code-intranet-issues#4]
![image](https://user-images.githubusercontent.com/1348687/31445828-3f495ae0-ae9f-11e7-977d-fb21269621f3.png)

Trying to change your Google Avatar is not possible for student accounts. Should be a problem with the permission settings.

**Comment by thomasbachem** [comment]
Fixed, you should now be allowed to do this. Google said it may take up to 24 hours until the setting is active though.
